# Generated by Django 4.1.4 on 2023-01-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hasTags', models.BooleanField()),
                ('postBody', models.TextField()),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('public', 'public'), ('draft', 'draft'), ('private', 'private')], max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GalleryPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hasTags', models.BooleanField()),
                ('postBody', models.TextField()),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('public', 'public'), ('draft', 'draft'), ('private', 'private')], max_length=15)),
                ('primaryImage', models.CharField(max_length=300)),
                ('thumbnail', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('hasTags', models.BooleanField()),
                ('postBody', models.TextField()),
                ('datePosted', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('public', 'public'), ('draft', 'draft'), ('private', 'private')], max_length=15)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('isActive', models.BooleanField()),
                ('profileLink', models.CharField(max_length=255)),
                ('thumbImg', models.CharField(max_length=300)),
                ('launch', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('isActive', models.BooleanField()),
                ('profileLink', models.CharField(max_length=255)),
                ('thumbImg', models.CharField(max_length=300)),
                ('username', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
