# Generated by Django 4.1.4 on 2023-01-11 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_blogposts_galleryposts_herosection_shoplinks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.galleryposts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='portfolio.blogposts')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
