# Generated by Django 4.1.4 on 2023-01-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_blogposts_dateposted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogposts',
            name='hasTags',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='galleryposts',
            name='hasTags',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hasTags',
            field=models.BooleanField(blank=True),
        ),
    ]
