# Generated by Django 4.1.4 on 2023-01-14 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_rename_blogposts_blogpost_rename_gallerytags_blogtag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogtag',
            name='post',
        ),
        migrations.RemoveField(
            model_name='gallerytag',
            name='post',
        ),
        migrations.AddField(
            model_name='blogtag',
            name='onPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portfolio.blogpost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallerytag',
            name='onPost',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='portfolio.gallerypost'),
            preserve_default=False,
        ),
    ]
