# Generated by Django 4.1.4 on 2023-01-14 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_remove_blogtag_post_remove_gallerytag_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='primaryImage',
            field=models.FileField(upload_to='gallery/images/'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='thumbnail',
            field=models.FileField(upload_to='gallery/thumbs/'),
        ),
    ]
