# Generated by Django 4.1.4 on 2023-01-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_gallerypost_primaryimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerypost',
            name='primaryImage',
            field=models.ImageField(upload_to='gallery/images/'),
        ),
        migrations.AlterField(
            model_name='gallerypost',
            name='thumbnail',
            field=models.ImageField(upload_to='gallery/thumbs/'),
        ),
    ]
